### ISSUE TITLE
Sorry to bother you, I need a syntax specification for OML.

### ISSUE THREAD

**Issue by username123wy** [opencaesar/oml#5]
## Description
Sorry to bother you, I need a syntax for OML.

## Expected Behavior
I want to learn the OML syntax deeply, so I want to the standard for OML, Do you have it or tell me how to get it. Really thanks for your help. 

## Additional Context
I want to learn the OML syntax deeply, so I want to the standard for OML, Do you have it or tell me how to get it. Really thanks for your help.

**Comment by username123wy** [comment]
Sorry to disturb you. Firstly , thank you for answering me questions before. 
When I run the ecore-adapter , one problem occurs and I do not know how to solve. Can you help me?
![testAttibuteEstring](https://user-images.githubusercontent.com/35055195/71570315-75dad180-2b0f-11ea-9bb6-c3cef2674d19.JPG)
This is the picture of ecore. The error is as follows:
![error](https://user-images.githubusercontent.com/35055195/71570325-8428ed80-2b0f-11ea-8c79-196527779357.JPG)
How can I solve this problem?

**Comment by melaasar** [comment]
Sorry to get back late to you on this. This issue is saying that it cannot resolve the XSD vocabulary.
When you run the Ecore-adapter, there is a paramater -w path/to/owl.oml that you need to pass. This represents a path to the owl.oml file (you can get that file by cloning the https://github.com/opencaesar/vocabularies) repo. This will get you all the OML dependencies that your ontologies will have so they can be resolved. Let me know if this is sufficient help or if you need more.

**Comment by melaasar** [comment]
The OML spec now includes the textual syntax: https://opencaesar.github.io/oml/#TextualSyntax
It will give you all the rules of the textual syntax.

**Comment by melaasar** [comment]
Not sure if this was sufficient to address your questions. Closing now, but feel free to reopen if you have further questions.
